checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'src/Contracts/*'
        - 'src/Exceptions/*'
        - 'src/Support/*'
        - 'src/Traits/*'
        - 'src/Config.php'
        - 'src/Helpers.php'
        - 'src/PDO.php'
build:
    tests:
        override:
            - command: ./vendor/bin/phpunit --verbose --coverage-text
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run